{% set version = "2.2.5" %}

package:
  name: zlib
  version: {{ version }}

source:
  url: https://codeload.github.com/zlib-ng/zlib-ng/tar.gz/refs/tags/{{ version }}
  sha256: 5b3b022489f3ced82384f06db1e13ba148cbce38c7941e424d6cb414416acd18
  fn: zstd-ng.tar.gz

build:
  string: {{ PKG_HASH }}_ng_{{ BUILD_NUMBER }}
  number: 0
  run_exports:
    # Just guessing since th library is so new
    # but they seem to want to be backward compatible
    # https://abi-laboratory.pro/index.php?view=timeline&l=zlib-ng
    - {{ pin_subpackage('zlib', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:

outputs:
  - name: zlib
  - name: libzlib  # just a shim for now
    requirements:
      run:
        - {{ pin_subpackage("zlib", exact=True) }}

test:
  commands:
    - test -e $PREFIX/include/zlib.h                         # [unix]
    - test -e $PREFIX/include/zconf.h                        # [unix]
    - test -e $PREFIX/lib/libz${SHLIB_EXT}                   # [unix]
    - test -e $PREFIX/lib/pkgconfig/zlib.pc                  # [unix]
    - if not exist %LIBRARY_INC%\zlib.h exit 1               # [win]
    - if not exist %LIBRARY_INC%\zconf.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\zlib1.dll exit 1            # [win]
    - if not exist %LIBRARY_LIB%\zlib.lib exit 1.            # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib.pc exit 1    # [win]

about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems

extra:
  recipe-maintainers:
    - hmaarrfk
